import type { Locale } from "./i18n";

export function getExploreCopy(locale: Locale) {
  return {
    en: {
      loading: "Loading live data...",
      empty: "The live service has no explorable workspaces right now.",
      title: "Data Explorer",
      start: "Start here",
      startTitle: "Pick a CSV and Loom will show three layers of facts.",
      startBody:
        "The left tree starts collapsed. Open a workspace, then a dataset, then a CSV file to inspect its data card, profile.json, and live raw table.",
      statsLabel: "Current live data overview",
      treeLabel: "Workspace / Dataset / File",
      treeAria: "Loom data tree",
      workspaceCommandLabel: "Pull this workspace",
      fileCommandLabel: "Get this file",
      tabAria: "File detail tabs",
      cardTab: "DataCard",
      profileTab: "Profile",
      rawTab: "Raw Data",
      step1Title: "Open a workspace",
      step1Body: "Start from live workspaces such as demo or energy to locate the source.",
      step2Title: "Choose a dataset",
      step2Body: "Open the dataset level to see the CSV files inside.",
      step3Title: "Inspect real data",
      step3Body: "Switch between DataCard, profile, and Raw Data.",
      workspaces: "Workspaces",
      datasets: "Datasets",
      files: "CSV files",
      datasetCount: "datasets",
      csvCount: "csv",
    },
    de: {
      loading: "Live-Daten werden geladen...",
      empty: "Der Live-Dienst hat derzeit keine erkundbaren Workspaces.",
      title: "Datenexplorer",
      start: "Hier starten",
      startTitle: "Wähle eine CSV und Loom zeigt drei Faktenebenen.",
      startBody:
        "Der linke Baum ist anfangs eingeklappt. Öffne zuerst einen Workspace, dann ein Dataset und schließlich eine CSV-Datei, um Datenkarte, profile.json und die Live-Rohtabelle zu sehen.",
      statsLabel: "Aktuelle Live-Datenübersicht",
      treeLabel: "Workspace / Dataset / Datei",
      treeAria: "Loom-Datenbaum",
      workspaceCommandLabel: "Diesen Workspace ziehen",
      fileCommandLabel: "Diese Datei holen",
      tabAria: "Dateidetail-Tabs",
      cardTab: "DataCard",
      profileTab: "Profil",
      rawTab: "Rohdaten",
      step1Title: "Workspace öffnen",
      step1Body: "Beginne mit Live-Workspaces wie demo oder energy, um die Quelle zu finden.",
      step2Title: "Dataset wählen",
      step2Body: "Öffne die Dataset-Ebene, um die enthaltenen CSV-Dateien zu sehen.",
      step3Title: "Echte Daten prüfen",
      step3Body: "Wechsle zwischen DataCard, Profil und Rohdaten.",
      workspaces: "Workspaces",
      datasets: "Datensätze",
      files: "CSV-Dateien",
      datasetCount: "Datensätze",
      csvCount: "CSV",
    },
    zh: {
      loading: "正在加载线上数据...",
      empty: "线上服务暂时没有可探索的工作区。",
      title: "数据探索",
      start: "START HERE",
      startTitle: "选择一个 CSV，Loom 会展示三层事实。",
      startBody: "左侧目录默认收起。先展开工作区，再展开数据集，最后选择一个 CSV 文件查看数据卡、profile.json 和线上原始表格。",
      statsLabel: "当前线上数据概览",
      treeLabel: "工作区 / 数据集 / 文件",
      treeAria: "Loom 数据树",
      workspaceCommandLabel: "拉取这个工作区",
      fileCommandLabel: "获取这个文件",
      tabAria: "文件详情标签",
      cardTab: "DataCard",
      profileTab: "profile",
      rawTab: "rawData",
      step1Title: "展开工作区",
      step1Body: "从 demo、energy 等线上工作区开始定位数据来源。",
      step2Title: "选择数据集",
      step2Body: "进入 dataset 层级，查看它包含的 CSV 文件。",
      step3Title: "查看真实数据",
      step3Body: "在 DataCard、profile 和 Raw Data 之间切换。",
      workspaces: "工作区",
      datasets: "数据集",
      files: "CSV 文件",
      datasetCount: "datasets",
      csvCount: "csv",
    },
  }[locale];
}
