from __future__ import annotations

import sqlalchemy as sa


metadata = sa.MetaData()
workspaces_table = sa.Table("loom_workspaces", metadata, sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(length=255), nullable=False, unique=True), sa.Column("head_revision_id", sa.String(length=64), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
workspace_revisions_table = sa.Table("loom_workspace_revisions", metadata, sa.Column("id", sa.Integer(), primary_key=True), sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("loom_workspaces.id"), nullable=False), sa.Column("revision_id", sa.String(length=64), nullable=False, unique=True), sa.Column("parent_revision_id", sa.String(length=64), nullable=True), sa.Column("tree_hash", sa.String(length=64), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("local_commit", sa.String(length=64), nullable=True), sa.Column("file_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
workspace_revision_files_table = sa.Table("loom_workspace_revision_files", metadata, sa.Column("id", sa.Integer(), primary_key=True), sa.Column("revision_id", sa.String(length=64), nullable=False), sa.Column("path", sa.Text(), nullable=False), sa.Column("sha256", sa.String(length=64), nullable=False), sa.Column("size_bytes", sa.Integer(), nullable=False), sa.Column("storage_path", sa.Text(), nullable=False))
raw_objects_table = sa.Table("loom_raw_objects", metadata, sa.Column("sha256", sa.String(length=64), primary_key=True), sa.Column("size_bytes", sa.Integer(), nullable=False), sa.Column("storage_path", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
workspace_raw_current_table = sa.Table("loom_workspace_raw_current", metadata, sa.Column("id", sa.Integer(), primary_key=True), sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("loom_workspaces.id"), nullable=False), sa.Column("path", sa.Text(), nullable=False), sa.Column("sha256", sa.String(length=64), nullable=False), sa.Column("size_bytes", sa.Integer(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("workspace_id", "path", name="uq_workspace_raw_current_path"))
workspace_raw_history_table = sa.Table("loom_workspace_raw_history", metadata, sa.Column("id", sa.Integer(), primary_key=True), sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("loom_workspaces.id"), nullable=False), sa.Column("revision_id", sa.String(length=64), nullable=True), sa.Column("path", sa.Text(), nullable=False), sa.Column("sha256", sa.String(length=64), nullable=True), sa.Column("size_bytes", sa.Integer(), nullable=True), sa.Column("action", sa.String(length=16), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
